import { createSignal } from "solid-js";

export function restaurantMenu() {
  const [menu] = createSignal([
    {name: 'Breakfast', menuImage: './assets/breakfast.jpg'},
    {name: 'Lunch', menuImage: './assets/lunch.jpeg'},
    {name: 'Dinner', menuImage: './assets/dinner.jpeg'},
    {name: 'Drinks', menuImage: './assets/drinks.jpeg'},
  ]);

  const [meal] = createSignal<Record<string, any[]>>(
    {
  "Luwombo": [
  {mealId: "1", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "2", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "3", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "4", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "5", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "6", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "7", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "8", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "9", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "10", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  ],
  "Katogo": [
  {mealId: "1", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "2", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "3", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "4", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "5", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "6", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "7", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "8", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "9", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "10", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  ],
  "Desserts": [
  {mealId: "1", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "2", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "3", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "4", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "5", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "6", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "7", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "8", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "9", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "10", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  ],
  "Asian foods": [
  {mealId: "1", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "2", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "3", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "4", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "5", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "6", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "7", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "8", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "9", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "10", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  ],
  "Sea food": [
  {mealId: "1", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "2", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "3", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "4", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "5", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "6", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "7", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "8", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "9", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  {mealId: "10", 
    mealName: 'Beef lasagne',
    mealImage: './assets/breakfast.jpg', 
    mealDescription: 'Delicious beef lasagne with double chilli. Served with a cold coke or juice. You should not miss out', 
    mealPrice: '4000', 
    quantity: '1'
  },
  ]
}
   
  );

  return {
    menu,
    meal,
  };
}